// In backend/routers/summaryRoutes.js
const express = require('express');
const router = express.Router();

// This is the endpoint that background.js will call
router.post('/summarize', (req, res) => {
    const { audio, transcript } = req.body;

    console.log("Received data from extension:");
    // In a real app, you would save this data to your database using your Models
    // For example: const newSummary = new Summary({ transcript }); await newSummary.save();

    console.log("Transcript:", transcript);

    // Send back a success response with a mock summary
    res.status(200).json({ 
        message: "Data received successfully!", 
        summary: "This is a summary generated by the backend." 
    });
});

module.exports = router;